import Head from "next/head";
import Image from "next/image";
import {
  CarouselProvider,
  Slider,
  Slide,
  ButtonBack,
  ButtonNext,
} from "pure-react-carousel";

const inDemandBooks = [
  {
    id: 1,
    name: "Basic Tee",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
  },
  {
    id: 2,
    name: "Basic Tee",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
  },
  {
    id: 3,
    name: "Basic Tee",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
  },
  {
    id: 4,
    name: "Basic Tee",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Home - Hero Section */}
      <section className="text-black body-font max-w-[1200px] mx-auto">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
            <h1 className="text-3xl md:text-5xl font-bold">
              <span className="text-indigo-500">Unlimited collection</span> of
              eBooks, Magazines and Books
            </h1>
            <p className="mb-8 mt-2 leading-relaxed text-xl">
              We carry thousands of titles available for free reading, allowing
              you access on virtually any platform at anytime, anywhere in the
              world!
            </p>
            <div className="flex w-full md:justify-start justify-center items-end">
              <div className="relative mr-4 md:w-full lg:w-full xl:w-1/2 w-2/4">
                <input
                  type="text"
                  id="hero-field"
                  name="hero-field"
                  placeholder="Your email"
                  className="w-full bg-gray-100 rounded border bg-opacity-50 border-gray-300 focus:ring-2 focus:ring-indigo-200 focus:bg-transparent focus:border-indigo-500 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                />
              </div>
              <button className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                Subscribe
              </button>
            </div>
            <p className="text-sm mt-2 text-gray-500 mb-8 w-full">
              Get latest eBooks directly on your email.
            </p>
            <div className="flex lg:flex-row md:flex-col">
              <button className="bg-gray-100 inline-flex py-3 px-5 rounded-lg items-center hover:bg-gray-200 focus:outline-none">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                  className="w-6 h-6"
                  viewBox="0 0 512 512"
                >
                  <path d="M99.617 8.057a50.191 50.191 0 00-38.815-6.713l230.932 230.933 74.846-74.846L99.617 8.057zM32.139 20.116c-6.441 8.563-10.148 19.077-10.148 30.199v411.358c0 11.123 3.708 21.636 10.148 30.199l235.877-235.877L32.139 20.116zM464.261 212.087l-67.266-37.637-81.544 81.544 81.548 81.548 67.273-37.64c16.117-9.03 25.738-25.442 25.738-43.908s-9.621-34.877-25.749-43.907zM291.733 279.711L60.815 510.629c3.786.891 7.639 1.371 11.492 1.371a50.275 50.275 0 0027.31-8.07l266.965-149.372-74.849-74.847z"></path>
                </svg>
                <span className="ml-4 flex items-start flex-col leading-none">
                  <span className="text-xs text-gray-600 mb-1">GET IT ON</span>
                  <span className="title-font font-medium">Google Play</span>
                </span>
              </button>
              <button className="bg-gray-100 inline-flex py-3 px-5 rounded-lg items-center lg:ml-4 md:ml-0 ml-4 md:mt-4 mt-0 lg:mt-0 hover:bg-gray-200 focus:outline-none">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                  className="w-6 h-6"
                  viewBox="0 0 305 305"
                >
                  <path d="M40.74 112.12c-25.79 44.74-9.4 112.65 19.12 153.82C74.09 286.52 88.5 305 108.24 305c.37 0 .74 0 1.13-.02 9.27-.37 15.97-3.23 22.45-5.99 7.27-3.1 14.8-6.3 26.6-6.3 11.22 0 18.39 3.1 25.31 6.1 6.83 2.95 13.87 6 24.26 5.81 22.23-.41 35.88-20.35 47.92-37.94a168.18 168.18 0 0021-43l.09-.28a2.5 2.5 0 00-1.33-3.06l-.18-.08c-3.92-1.6-38.26-16.84-38.62-58.36-.34-33.74 25.76-51.6 31-54.84l.24-.15a2.5 2.5 0 00.7-3.51c-18-26.37-45.62-30.34-56.73-30.82a50.04 50.04 0 00-4.95-.24c-13.06 0-25.56 4.93-35.61 8.9-6.94 2.73-12.93 5.09-17.06 5.09-4.64 0-10.67-2.4-17.65-5.16-9.33-3.7-19.9-7.9-31.1-7.9l-.79.01c-26.03.38-50.62 15.27-64.18 38.86z"></path>
                  <path d="M212.1 0c-15.76.64-34.67 10.35-45.97 23.58-9.6 11.13-19 29.68-16.52 48.38a2.5 2.5 0 002.29 2.17c1.06.08 2.15.12 3.23.12 15.41 0 32.04-8.52 43.4-22.25 11.94-14.5 17.99-33.1 16.16-49.77A2.52 2.52 0 00212.1 0z"></path>
                </svg>
                <span className="ml-4 flex items-start flex-col leading-none">
                  <span className="text-xs text-gray-600 mb-1">
                    Download on the
                  </span>
                  <span className="title-font font-medium">App Store</span>
                </span>
              </button>
            </div>
          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            {/* Start: Animated Image with blobs */}
            <div className="relative flex justify-end">
              <img
                className="object-cover object-center rounded"
                alt="Book"
                height={600}
                width={320}
                src="/images/home-hero-book.png"
              />

              <svg
                viewBox="0 0 200 200"
                xmlns="http://www.w3.org/2000/svg"
                className="animate-[spin_10s_linear_infinite] absolute top-0 -z-10"
              >
                <path
                  fill="#e0e7ff"
                  d="M38.8,-50.5C51.7,-44,64.5,-34.6,67.1,-22.7C69.7,-10.8,62.1,3.4,56.4,17.5C50.7,31.6,46.9,45.5,37.8,57.9C28.7,70.4,14.4,81.5,0.2,81.2C-13.9,81,-27.9,69.2,-42.3,58.5C-56.6,47.7,-71.5,37.9,-78,23.9C-84.5,9.9,-82.6,-8.2,-74.4,-21.3C-66.2,-34.5,-51.7,-42.8,-38.2,-49.1C-24.7,-55.4,-12.4,-59.8,0.3,-60.2C13,-60.6,25.9,-57,38.8,-50.5Z"
                  transform="translate(100 100)"
                />
              </svg>

              <svg
                viewBox="0 0 200 200"
                xmlns="http://www.w3.org/2000/svg"
                className="animate-[spin_8s_linear_infinite] absolute top-0 -z-10"
              >
                <path
                  fill="#a5b4fc"
                  d="M38.8,-50.5C51.7,-44,64.5,-34.6,67.1,-22.7C69.7,-10.8,62.1,3.4,56.4,17.5C50.7,31.6,46.9,45.5,37.8,57.9C28.7,70.4,14.4,81.5,0.2,81.2C-13.9,81,-27.9,69.2,-42.3,58.5C-56.6,47.7,-71.5,37.9,-78,23.9C-84.5,9.9,-82.6,-8.2,-74.4,-21.3C-66.2,-34.5,-51.7,-42.8,-38.2,-49.1C-24.7,-55.4,-12.4,-59.8,0.3,-60.2C13,-60.6,25.9,-57,38.8,-50.5Z"
                  transform="translate(100 100)"
                />
              </svg>

              <svg
                viewBox="0 0 200 200"
                xmlns="http://www.w3.org/2000/svg"
                className="animate-[spin_9s_linear_infinite] absolute top-0 -z-10"
              >
                <path
                  fill="#818CF8"
                  d="M38.8,-50.5C51.7,-44,64.5,-34.6,67.1,-22.7C69.7,-10.8,62.1,3.4,56.4,17.5C50.7,31.6,46.9,45.5,37.8,57.9C28.7,70.4,14.4,81.5,0.2,81.2C-13.9,81,-27.9,69.2,-42.3,58.5C-56.6,47.7,-71.5,37.9,-78,23.9C-84.5,9.9,-82.6,-8.2,-74.4,-21.3C-66.2,-34.5,-51.7,-42.8,-38.2,-49.1C-24.7,-55.4,-12.4,-59.8,0.3,-60.2C13,-60.6,25.9,-57,38.8,-50.5Z"
                  transform="translate(100 100)"
                />
              </svg>
            </div>
            {/* End: Animated Image with blobs */}
          </div>
        </div>
      </section>
      {/* Home - Hero Section */}

      {/* Resources */}
      <section className="bg-gray-100">
        <div className="flex items-center justify-center text-center ">
          <div className="flex flex-col p-2 m-2 ">
            <h1 className="text-3xl md:text-5xl font-bold text-center mb-5">
              Reading <span className="text-indigo-500">Resources</span>
            </h1>

            <div className="text-sm mx-2 md:text-xl mb-2">
              Enjoy free content in different formats
            </div>
            <div className="md:grid flex">
              <div className="flex space-x-4  p-2 items-center justify-center md:flex-row flex-col ">
                <div className="flex-col px-6 py-2 ">
                  <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200">
                    <Image
                      src="/images/resources-ebooks.jpg"
                      height={150}
                      width={150}
                      className="object-cover w-full h-full"
                      alt="eBooks Collection"
                    />
                  </div>

                  <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">
                    EBooks
                  </div>
                </div>
                <div className="flex-col px-6 py-2 ">
                  <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200">
                    <Image
                      src="/images/resources-magazines.jpg"
                      height={150}
                      width={150}
                      className="object-cover w-full h-full"
                      alt="Magazines Collection"
                    />
                  </div>

                  <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">
                    Magazines
                  </div>
                </div>
                <div className="flex-col px-6 py-2 ">
                  <div className="md:h-40 h-28 w-28 md:w-40 rounded-full overflow-hidden bg-gray-200">
                    <Image
                      src="/images/resources-books.jpg"
                      height={150}
                      width={150}
                      className="object-cover w-full h-full"
                      alt="Books Collection"
                    />
                  </div>

                  <div className="text-lg font-medium text-stone-600 cursor-pointer hover:text-stone-400">
                    Books
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* End Resources */}

      {/* Most Demanding */}
      <section>
        <div className="bg-white">
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h1 className="text-3xl md:text-5xl font-bold text-center mb-5">
              Books in <span className="text-indigo-500">Demand</span>
            </h1>

            {/* <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8"> */}
            <div>
              <CarouselProvider
                naturalSlideWidth={100}
                naturalSlideHeight={40}
                totalSlides={inDemandBooks.length}
                visibleSlides={4}
                infinite={true}
                isIntrinsicHeight={true}
                interval={1000}
                isPlaying={true}
              >
                <Slider>
                  {inDemandBooks.map((product) => (
                    <Slide index={product.id - 1} key={product.id}>
                      <div key={product.id} className="group relative mx-2">
                        <div className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
                          <img
                            src={product.imageSrc}
                            alt={product.imageAlt}
                            className="h-full w-full object-center lg:h-full lg:w-full"
                          />
                        </div>
                        <div className="mt-4 flex justify-between">
                          <div>
                            <h3 className="text-sm text-gray-700">
                              <a href={product.href}>
                                <span
                                  aria-hidden="true"
                                  className="absolute inset-0"
                                />
                                {product.name}
                              </a>
                            </h3>
                            <p className="mt-1 text-sm text-gray-500">
                              {product.color}
                            </p>
                          </div>
                          <p className="text-sm font-medium text-gray-900">
                            {product.price}
                          </p>
                        </div>
                      </div>
                    </Slide>
                  ))}
                </Slider>
              </CarouselProvider>
            </div>
          </div>
        </div>
      </section>
      {/* End Most Demanding */}

      {/* Blogs */}
      <section className="text-gray-600 body-font bg-gray-100">
        <div className="container px-5 py-24 mx-auto max-w-[1200px]">
          <div className="flex flex-wrap -m-4">
            <div className="p-4 lg:w-1/3">
              <div className="h-full bg-white bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
                <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                  CATEGORY
                </h2>
                <h1 className="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">
                  Raclette Blueberry Nextious Level
                </h1>
                <p className="leading-relaxed mb-3">
                  Photo booth fam kinfolk cold-pressed sriracha leggings
                  jianbing microdosing tousled waistcoat.
                </p>
                <a className="text-indigo-500 inline-flex items-center">
                  Learn More
                  <svg
                    className="w-4 h-4 ml-2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M5 12h14"></path>
                    <path d="M12 5l7 7-7 7"></path>
                  </svg>
                </a>
                <div className="text-center mt-2 leading-none flex justify-center absolute bottom-0 left-0 w-full py-4">
                  <span className="text-gray-400 mr-3 inline-flex items-center leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                    <svg
                      className="w-4 h-4 mr-1"
                      stroke="currentColor"
                      strokeWidth="2"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                      <circle cx="12" cy="12" r="3"></circle>
                    </svg>
                    1.2K
                  </span>
                  <span className="text-gray-400 inline-flex items-center leading-none text-sm">
                    <svg
                      className="w-4 h-4 mr-1"
                      stroke="currentColor"
                      strokeWidth="2"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                    </svg>
                    6
                  </span>
                </div>
              </div>
            </div>
            <div className="p-4 lg:w-1/3">
              <div className="h-full bg-white bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
                <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                  CATEGORY
                </h2>
                <h1 className="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">
                  Ennui Snackwave Thundercats
                </h1>
                <p className="leading-relaxed mb-3">
                  Photo booth fam kinfolk cold-pressed sriracha leggings
                  jianbing microdosing tousled waistcoat.
                </p>
                <a className="text-indigo-500 inline-flex items-center">
                  Learn More
                  <svg
                    className="w-4 h-4 ml-2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M5 12h14"></path>
                    <path d="M12 5l7 7-7 7"></path>
                  </svg>
                </a>
                <div className="text-center mt-2 leading-none flex justify-center absolute bottom-0 left-0 w-full py-4">
                  <span className="text-gray-400 mr-3 inline-flex items-center leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                    <svg
                      className="w-4 h-4 mr-1"
                      stroke="currentColor"
                      strokeWidth="2"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                      <circle cx="12" cy="12" r="3"></circle>
                    </svg>
                    1.2K
                  </span>
                  <span className="text-gray-400 inline-flex items-center leading-none text-sm">
                    <svg
                      className="w-4 h-4 mr-1"
                      stroke="currentColor"
                      strokeWidth="2"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                    </svg>
                    6
                  </span>
                </div>
              </div>
            </div>
            <div className="p-4 lg:w-1/3">
              <div className="h-full bg-white bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
                <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                  CATEGORY
                </h2>
                <h1 className="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">
                  Selvage Poke Waistcoat Godard
                </h1>
                <p className="leading-relaxed mb-3">
                  Photo booth fam kinfolk cold-pressed sriracha leggings
                  jianbing microdosing tousled waistcoat.
                </p>
                <a className="text-indigo-500 inline-flex items-center">
                  Learn More
                  <svg
                    className="w-4 h-4 ml-2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M5 12h14"></path>
                    <path d="M12 5l7 7-7 7"></path>
                  </svg>
                </a>
                <div className="text-center mt-2 leading-none flex justify-center absolute bottom-0 left-0 w-full py-4">
                  <span className="text-gray-400 mr-3 inline-flex items-center leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                    <svg
                      className="w-4 h-4 mr-1"
                      stroke="currentColor"
                      strokeWidth="2"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                      <circle cx="12" cy="12" r="3"></circle>
                    </svg>
                    1.2K
                  </span>
                  <span className="text-gray-400 inline-flex items-center leading-none text-sm">
                    <svg
                      className="w-4 h-4 mr-1"
                      stroke="currentColor"
                      strokeWidth="2"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      viewBox="0 0 24 24"
                    >
                      <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                    </svg>
                    6
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* End Blogs */}

      {/* Diverse Categories */}
      <section className="max-w-[1200px] mx-auto">
        <div className="flex justify-center ">
          <nav className="self-center w-full max-w-7xl  ">
            <div className="flex flex-col lg:flex-row justify-around items-center border-b-2">
              <h1 className="uppercase pl-5 py-4 text-xl font-sans font-bold">
                Diverse Range
              </h1>
              <ul className="hidden lg:flex items-center text-[18px] font-semibold pl-32">
                <li className="hover:underline  underline-offset-4 decoration-2 decoration-black py-2 rounded-lg px-5">
                  <a href="#">Editor's Pick</a>
                </li>
                <li className="hover:underline underline-offset-4 decoration-2 decoration-black py-2 rounded-lg px-5">
                  <a href="#">Art</a>
                </li>
                <li className="hover:underline underline-offset-4 decoration-2 decoration-black py-2 rounded-lg px-5">
                  <a href="#">Science</a>
                </li>
                <li className="hover:underline underline-offset-4 decoration-2 decoration-black py-2 rounded-lg px-5">
                  <a href="#">Children</a>
                </li>
                <li className="hover:underline underline-offset-4 decoration-2 decoration-black py-2 rounded-lg px-5">
                  <a href="#">Personal Growth</a>
                </li>

                <li className="hover:underline underline-offset-4 decoration-2 decoration-indigo-500 text-indigo-500 py-2 rounded-lg px-5">
                  <a href="#">View All</a>
                </li>
              </ul>
              <div className=" text-center text-base pr-5  inline-flex">
                <a
                  href="#"
                  className="w-8 h-8 inline-block rounded-full pt-[6px] hover:text-blue-500"
                >
                  <i className="fa fa-twitter"></i>
                </a>
                <a
                  href="#"
                  className="w-8 h-8 inline-block rounded-full pt-[5px] hover:text-blue-500"
                >
                  <i className="fa fa-instagram"></i>
                </a>
                <a
                  href="#"
                  className="w-8 h-8 inline-block rounded-full pt-[5px] hover:text-blue-500"
                >
                  <i className="fa fa-facebook"></i>
                </a>
                <a
                  href="#"
                  className="w-8 h-8 inline-block rounded-full pt-[5px] hover:text-blue-500"
                >
                  <i className="fa fa-google"></i>
                </a>
                <a
                  href="#"
                  className="w-8 h-8 inline-block rounded-full pt-[5px] hover:text-blue-500"
                >
                  <i className="fa fa-linkedin"></i>
                </a>
              </div>
            </div>
          </nav>
        </div>
        <div className="flex justify-center mt-4">
          <div className="flex flex-col items-center justify-center">
            <div className="flex flex-col  max-w-7xl justify-center items-center space-y-3 w-full ">
              <div className="flex flex-col   md:items-start items-center justify-center  space-y-3 px-8 text-center ">
                <div className="text-3xl md:text-5xl font-bold">
                  Browse <span className="text-indigo-500">Diverse</span>{" "}
                  Collection of Digital Assets
                </div>
              </div>
              <div className="flex flex-col lg:flex-row space-x-2 space-y-3 md:space-x-6   w-full items-center justify-center ">
                <div className="lg:w-40 w-64 h-40  overflow-hidden rounded-xl ">
                  <img
                    src="https://source.unsplash.com/random/300x500/?man

                  "
                    alt=""
                    className=""
                  />
                </div>
                <div className="flex flex-row lg:flex-col space-x-3 space-y-6 items-center justify-center">
                  <div className="w-32 lg:w-40 h-32  overflow-hidden rounded-xl ">
                    <img
                      src="https://source.unsplash.com/random/300x500/?man

                      "
                      alt=""
                      className=""
                    />
                  </div>
                  <div className="w-32 lg:w-40 h-48  overflow-hidden rounded-xl ">
                    <img
                      src="https://source.unsplash.com/random/300x500/?man

                      "
                      alt=""
                      className=""
                    />
                  </div>
                </div>
                <div className="lg:w-60 w-64 h-96  overflow-hidden rounded-xl ">
                  <img
                    src="https://source.unsplash.com/random/300x500/?man

                  "
                    alt=""
                    className=""
                  />
                </div>
                <div className="flex flex-row lg:flex-col space-x-3 space-y-6 items-center justify-center ">
                  <div className="w-32 lg:w-40 h-48  overflow-hidden rounded-xl ">
                    <img
                      src="https://source.unsplash.com/random/300x500/?man

                      "
                      alt=""
                      className=""
                    />
                  </div>
                  <div className="w-32 lg:w-40 h-32  overflow-hidden rounded-xl ">
                    <img
                      src="https://source.unsplash.com/random/300x500/?man

                      "
                      alt=""
                      className=""
                    />
                  </div>
                </div>
                <div className="lg:w-40 w-64 h-40  overflow-hidden rounded-xl ">
                  <img
                    src="https://source.unsplash.com/random/300x500/?man

                  "
                    alt=""
                    className=""
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* End Diverse Categories */}

      {/* Banner Section */}
      <section className="text-gray-600 body-font max-w-[1200px] mx-auto">
        <div className="container px-5 py-24 mx-auto flex flex-col">
          <div className="rounded-lg h-64 overflow-hidden">
            <img
              alt="content"
              className="object-cover object-center h-full w-full"
              // src="https://images.pexels.com/photos/1887609/pexels-photo-1887609.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
              src="https://connect-assets.prosple.com/cdn/ff/amLER-yt518MBUpoSKGiuzjfBEL8wgN7SySHnOBiQZE/1598585167/public/2020-08/TwitterCover3.jpg"
            />
          </div>
        </div>
      </section>
      {/* End Banner Section */}

      {/* Statistics */}
      <section className="text-gray-600 body-font max-w-[1200px] mx-auto">
        <div className="container px-5 py-24 mx-auto flex flex-wrap">
          <div className="flex flex-wrap -mx-4 mt-auto mb-auto lg:w-1/2 sm:w-2/3 content-start sm:pr-10">
            <div className="w-full sm:p-4 px-4 mb-6">
              <h1 className="title-font font-medium text-xl mb-2 text-gray-900">
                Be a part of the huge community of Book Lovers
              </h1>
              <div className="leading-relaxed">
                We are growing day by day, uploading new content on daily basis and introducing new features for our community members.
              </div>
            </div>
            <div className="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
              <h2 className="title-font font-medium text-3xl text-gray-900">
                2.7K
              </h2>
              <p className="leading-relaxed">Resources</p>
            </div>
            <div className="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
              <h2 className="title-font font-medium text-3xl text-gray-900">
                1.8K
              </h2>
              <p className="leading-relaxed">Subscribes</p>
            </div>
            <div className="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
              <h2 className="title-font font-medium text-3xl text-gray-900">
                35K
              </h2>
              <p className="leading-relaxed">Downloads</p>
            </div>
            <div className="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
              <h2 className="title-font font-medium text-3xl text-gray-900">
                421k
              </h2>
              <p className="leading-relaxed">Reviews</p>
            </div>
          </div>
          <div className="lg:w-1/2 sm:w-1/3 w-full rounded-lg mt-6 sm:mt-0">
            <div className="relative flex align-bottom justify-center h-full">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                className="w-full max-w-[500px] absolute -bottom-20"
                // src="https://dummyimage.com/600x300"
                src="/images/statistics-book.png"
                alt="stats"
              />
              
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                // className="object-cover object-center absolute top-0 h-auto w-full max-w-[400px] animate-[bounce_10s_linear_infinite]"
                className="object-cover object-center absolute -top-10 h-auto w-full max-w-[400px] animate-[linear-bounce_10s_linear_infinite]"
                // src="https://dummyimage.com/600x300"
                src="/images/statistics-graphs.png"
                alt="stats"
              />
            </div>
          </div>
        </div>
      </section>
      {/* End Statistics */}

      {/* Newsletter */}
      <section className="text-gray-600 body-font bg-gray-100">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center max-w-[1200px] mx-auto">
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
            <img
              className="object-cover object-center rounded"
              alt="hero"
              // src="https://dummyimage.com/720x600"
              src="/images/newsletter-image.jpg"
            />
          </div>
          <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-bold text-gray-900">
              Get an <strong>eBook</strong> directly{" "}
              <span class="text-indigo-500">on your Email</span>
            </h1>
            <p className="mb-8 leading-relaxed">
              Enjoy your weekends by reading the most popular book of the week
              sent on your email. Just download, relax and read.
            </p>
            <div className="flex w-full md:justify-start justify-center items-end">
              <div className="relative mr-4 lg:w-full xl:w-1/2 w-2/4">
                <label
                  for="hero-field"
                  className="leading-7 text-sm text-gray-600"
                >
                  Subscribe!
                </label>
                <input
                  type="text"
                  id="hero-field"
                  name="hero-field"
                  placeholder="Your email"
                  className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:ring-2 focus:ring-indigo-200 focus:bg-transparent focus:border-indigo-500 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                />
              </div>
              <button className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                Subscribe
              </button>
            </div>
            <p className="text-sm mt-2 text-gray-500 mb-8 w-full">
              Get popular eBooks directly on your email.
            </p>
          </div>
        </div>
      </section>
      {/* End Newsletter */}

      {/* Testimonials */}
      <section className="text-gray-600 body-font max-w-[1200px] mx-auto">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap -m-4">
            <div className="lg:w-1/3 lg:mb-0 mb-6 p-4">
              <div className="h-full text-center">
                <img
                  alt="testimonial"
                  className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                  src="https://dummyimage.com/302x302"
                />
                <p className="leading-relaxed">
                  Edison bulb retro cloud bread echo park, helvetica stumptown
                  taiyaki taxidermy 90's cronut +1 kinfolk. Single-origin coffee
                  ennui shaman taiyaki vape DIY tote bag drinking vinegar cronut
                  adaptogen squid fanny pack vaporware.
                </p>
                <span className="inline-block h-1 w-10 rounded bg-indigo-500 mt-6 mb-4"></span>
                <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                  HOLDEN CAULFIELD
                </h2>
                <p className="text-gray-500">Senior Product Designer</p>
              </div>
            </div>
            <div className="lg:w-1/3 lg:mb-0 mb-6 p-4">
              <div className="h-full text-center">
                <img
                  alt="testimonial"
                  className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                  src="https://dummyimage.com/300x300"
                />
                <p className="leading-relaxed">
                  Edison bulb retro cloud bread echo park, helvetica stumptown
                  taiyaki taxidermy 90's cronut +1 kinfolk. Single-origin coffee
                  ennui shaman taiyaki vape DIY tote bag drinking vinegar cronut
                  adaptogen squid fanny pack vaporware.
                </p>
                <span className="inline-block h-1 w-10 rounded bg-indigo-500 mt-6 mb-4"></span>
                <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                  ALPER KAMU
                </h2>
                <p className="text-gray-500">UI Develeoper</p>
              </div>
            </div>
            <div className="lg:w-1/3 lg:mb-0 p-4">
              <div className="h-full text-center">
                <img
                  alt="testimonial"
                  className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                  src="https://dummyimage.com/305x305"
                />
                <p className="leading-relaxed">
                  Edison bulb retro cloud bread echo park, helvetica stumptown
                  taiyaki taxidermy 90's cronut +1 kinfolk. Single-origin coffee
                  ennui shaman taiyaki vape DIY tote bag drinking vinegar cronut
                  adaptogen squid fanny pack vaporware.
                </p>
                <span className="inline-block h-1 w-10 rounded bg-indigo-500 mt-6 mb-4"></span>
                <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                  HENRY LETHAM
                </h2>
                <p className="text-gray-500">CTO</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* End Testimonials */}

      {/* Location */}
      <section className="text-gray-600 body-font relative">
        <div className="absolute inset-0 bg-gray-300">
          <iframe
            width="100%"
            height="100%"
            frameborder="0"
            marginHeight="0"
            marginWidth="0"
            title="map"
            scrolling="no"
            src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=%C4%B0zmir+(My%20Business%20Name)&ie=UTF8&t=&z=14&iwloc=B&output=embed"
            // style={{ filter: 'grayscale(1) contrast(1.2) opacity(0.4)' }}
          ></iframe>
        </div>
        <div className="container px-5 py-24 mx-auto flex">
          <div className="lg:w-1/3 md:w-1/2 bg-white rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0 relative z-10 shadow-md">
            <h2 className="text-gray-900 text-lg mb-1 font-medium title-font">
              Opening Hours
            </h2>
            <p className="leading-relaxed mb-5 text-gray-600">
              Following is the library schedule for all the branches.
            </p>
            <div>
              {[
                { day: "Monday", time: "08AM - 10PM" },
                { day: "Tuesday", time: "08AM - 10PM" },
                { day: "Wednesday", time: "10AM - 08PM" },
                { day: "Thursday", time: "09AM - 06PM" },
                { day: "Friday", time: "09AM - 10PM" },
                { day: "Saturday", time: "10AM - 08PM" },
                { day: "Sunday", time: "Closed" },
              ].map((openingHour, index) => (
                <h4
                  className="font-bold py-2 hover:text-indigo-500 text-sm flex justify-between items-center"
                  key={index}
                >
                  {openingHour.day}
                  <span
                    className={
                      openingHour.time.toLowerCase() == "closed"
                        ? "text-red-500"
                        : ""
                    }
                  >
                    {openingHour.time}
                  </span>
                </h4>
              ))}
            </div>
          </div>
        </div>
      </section>
      {/* Location */}
    </>
  );
}
